### ISSUE TITLE
implement basic todo list

### ISSUE THREAD

**Issue by the-lee-jackson** [the-lee-jackson/vienna#2]
### Note
The below description represents the _next steps_ in the project. The implemented functionality is only a main list, not more than one list with profiles.

### Description

Branch name: `implement-todo-list`

Given a list of todo items, it should list all items and have basic interaction with the items.

A _todo list_ is composed of _todo items_. We can have a list named "shopping list" with shopping items and a list named "movies to watch" with movies that we want to watch in the following days, etc. But when we are at work we don't want to be bothered by the list "movies to watch" because it is not part of the current activities that we do at work. So, from this observation, the ideea of "profiles" follows naturally. A profile is like a _context_, depending on what we do at the moment, and where we are, and what state of mind are we in, we want to interact with just a subset of the lists. A **profile** is a collection of lists. Example profiles could include "work", "school", "fun time", etc.

A `TODO_ITEM` has the following structure (_described in pseudocode_):
```javascript
TODO_ITEM {
  - ID: STRING // an UUID value
  - TEXT: STRING;
  - ADDED_AT: DATE;
  - MODIFIED_AT: DATE; // when created, this value will be the same as ADDED_AT
  - STATUS: { TODO, IN_PROGRESS, DONE }; // a simple enum, values represented as strings like 'TODO', etc.
  - OLD_STATUS: { TODO, IN_PROGRESS, DONE, null /* if no old status present i.e. just added */ };
}
```

A `TODO_LIST` has the following structure (_described in pseudocode_):
```javascript
TODO_LIST {
  - ID: STRING // an UUID value
  - ITEMS: [TODO_ITEM] // a list of one or more TODO_ITEM (described above)
  - DESC: STRING // the list description
  - NAME: STRING // the name of the list
  - COLOR: STRING // the color of the list (from a predefined list of colors)
  - PROFILES: [PROFILE_ID] // a list of profile IDs (see PROFILE section)
  - NR_TODO: NUMBER // how many items in the list have the status 'TODO' 
  - NR_IN_PROGRESS: NUMBER // how many items in the list have the status 'IN_PROGRESS' 
  - NR_DONE: NUMBER // how many items in the list have the status 'DONE' 
}
```

A `PROFILE` has the following structure (_described in pseudocode_):
```javascript
PROFILE {
  - ID: STRING // an UUID value
  - NAME: STRING // the name of the profile
  - DESC: STRING // the description of the profile;
}
```

Subtasks for this issue:
---
- [x] add **JS** lib that generates _UUID_ values;
- [x] create todo store and add actions and getters for working with the todo store;
- [x] create the basic list;
