### ISSUE TITLE
Add simple export functionality to JSON format.

### ISSUE THREAD

**Issue by the-lee-jackson** [the-lee-jackson/vienna#4]
The user must be able to export all data to a json file to backup.

### Subtasks

- [x] add export page;
- [x] add export form;
- [x] add generation and download functionality
